services:
  - type: web
    name: hotel-camp-friends-corner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "hotel-camp-friends-corner.onrender.com"